### ISSUE TITLE
Error: "No module named 'unidam'"

### ISSUE THREAD

**Issue by mlldantas** [minzastro/unidam#9] opened 2021-11-22 12:39 UTC
Hello,

I am trying to use unidam, but I am having a few problems. I followed the instructions [here](https://github.com/minzastro/unidam/wiki), but when I finally try to run unidam, I get the following error message:

```
File "./unidam/unidam/core/unidam_runner.py", line 23, in <module>
    from unidam.core.model_fitter import model_fitter as mf
ModuleNotFoundError: No module named 'unidam'
```

I talked to someone who installed your package sometime ago and I was told I needed to install [this](https://github.com/minzastro/skewnorm_boost), but I did not see it in the wiki.

Could you please give me a hand with this?

Thanks so much! Have a great week!

**Comment by minzastro** [comment] 2021-11-22 13:14
@mlldantas Thank you for your interest! The error you get seem to be caused by missing *.so files - those produced by build_fortran.sh, something like "model_fitter.cpython-38-x86_64-linux-gnu.so". If they are not in unidam/core, this means that fortran compilation failed. If they are present, you'll need to copy/link them to ~/.local/lib/python???/site-packages/unidam or wherever unidam was installed. I had no time/will to make setup.py do that automatically.

**Comment by mlldantas** [comment] 2021-11-22 13:45
Hi @minzastro,

Thanks so much for your reply! So, you bring me back to a previous problem, which is the overall installation of unidam. I had compiled the .sh files you mentioned in your wiki, but unidam does not install with pip/anaconda/git. So I figured I needed to use it in the same directory that I am running it.

According to your answer, unidam should be installed along with other python packages. In this case, you are saying I should just move the folder to my python packages path. Do you confirm this?

Also, I tried compiling the `build_fortran.sh` once again and I printed the messages in a file and I am attaching it to this message. There are indeed several warnings, but I am not sure what is causing it not to generate the appropriate files.

[log_unidam.txt](https://github.com/minzastro/unidam/files/7581606/log_unidam.txt)

Thanks so much for your time again!

**Comment by minzastro** [comment] 2021-11-22 21:47
Technically you should be able to run "python setup.py install --user", which should install UniDAM to your .local folder, but I am not certain how this will work with Anaconda.
Anyway, in order to run properly, unidam folder (the one with __init__.py, skewnorm_boosted.py and  studentst_boosted.py) should be in your PYTHONPATH.
I do not see any critical messages in your log file - if .so files are created, everything should be ok. f2py tends to be rather verbose.

**Comment by minzastro** [comment] 2021-11-23 09:08
btw, I noticed a bug that somehow got into unidam_main.py, which is fixed in the latest commit (from yesterday). Please update your code.

**Comment by mlldantas** [comment] 2021-11-23 12:07
Hi @minzastro,

I will check everything you told me this afternoon. I will get back to you tomorrow the latest saying whether I managed to solve this or not. 

Thanks so much again for your time!

**Comment by mlldantas** [comment] 2021-11-23 19:17
Hi @minzastro ,

I have a new problem. :-)
I downloaded the newest version of unidam.
I am running the installation as you suggested above, directly with python, and I get the following error message:

> error: file '/work/mlldantas/Documents/Projects/CHESS/Codes/unidam/unidam/iso/unidam_runner.py' does not exist

I tried both techniques, installing first and running `build_fortran.sh` and vice-versa. In both cases I got the above message.
`skewnorm_boosted.py ` and ` studentst_boosted.py` are both there in ~/unidam/unidam, which currently is my local file, not where I usually install my python packages.

The installation output is [here](https://github.com/minzastro/unidam/files/7590491/log_unidam.txt)

I can't test it further as it didn't generate or come with `unidam_runner.py`.

**Comment by minzastro** [comment] 2021-11-23 22:06
@mlldantas , it seems my setup.py script was rather old - I did quite a bit of refactoring since I last run it myself. I have updated it so that it should work properly. Please make sure to remove all already installed unidam files - at least on my linux machine the updated setup.py creates a python egg with a name that is different from the old one, thus there is a risk of having two unidams  :) .

**Comment by mlldantas** [comment] 2021-11-24 14:26
Hi @minzastro ,

Thanks so much for your reply. 
Unidam seems to be working properly now. :-)

I have just another question. I would like to know if the extinction is mandatory in the input fits file. I had the impression it was optional, and I didn't retrieve it. I tried running unidam after another installation and it started "thinking" (which I think is a good sign), but then it complained about the extinction field (I commented these lines in the config file).

> Traceback (most recent call last):
>   File "/work/mlldantas/anaconda3/lib/python3.8/configparser.py", line 789, in get
>     value = d[option]
>   File "/work/mlldantas/anaconda3/lib/python3.8/collections/__init__.py", line 898, in __getitem__
>     return self.__missing__(key)            # support subclasses that define __missing__
>   File "/work/mlldantas/anaconda3/lib/python3.8/collections/__init__.py", line 890, in __missing__
>     raise KeyError(key)
> KeyError: 'column'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "./unidam-master/unidam/core/unidam_runner.py", line 69, in <module>
>     de = UniDAMTool(config_filename=args.config, config_override=override)
>   File "/work/mlldantas/anaconda3/lib/python3.8/site-packages/unidam-1.0-py3.8-linux-x86_64.egg/unidam/core/unidam_main.py", line 152, in __init__
>     self._update_config('extinction', config)
>   File "/work/mlldantas/anaconda3/lib/python3.8/site-packages/unidam-1.0-py3.8-linux-x86_64.egg/unidam/core/unidam_main.py", line 213, in _update_config
>     self.config[name] = config.get(name, 'column')
>   File "/work/mlldantas/anaconda3/lib/python3.8/configparser.py", line 792, in get
>     raise NoOptionError(option, section)
> configparser.NoOptionError: No option 'column' in section: 'extinction'


Let me know the best way to configure that.

Thanks!

**Comment by mlldantas** [comment] 2021-11-24 15:30
Hi @minzastro ,

I guess I found what can be the problem now. I was using the parallax but not the extinction (if I understood correctly, in order to use the parallax I must use the extinction). I tried re-configuring the config file to remove the parallax as well and I got the following error message:

> Traceback (most recent call last):
>   File "./unidam-master/unidam/core/unidam_runner.py", line 69, in <module>
>     de = UniDAMTool(config_filename=args.config, config_override=override)
>   File "/work/mlldantas/anaconda3/lib/python3.8/site-packages/unidam-1.0-py3.8-linux-x86_64.egg/unidam/core/unidam_main.py", line 170, in __init__
>     mf.max_param_err = config.getint('general', 'max_param_err')
>   File "/work/mlldantas/anaconda3/lib/python3.8/configparser.py", line 818, in getint
>     return self._get_conv(section, option, int, raw=raw, vars=vars,
>   File "/work/mlldantas/anaconda3/lib/python3.8/configparser.py", line 808, in _get_conv
>     return self._get(section, conv, option, raw=raw, vars=vars,
>   File "/work/mlldantas/anaconda3/lib/python3.8/configparser.py", line 803, in _get
>     return conv(self.get(section, option, **kwargs))
> ValueError: invalid literal for int() with base 10: '4.'

Thanks again for your help!

**Comment by minzastro** [comment] 2021-11-24 18:14
@mlldantas the last problem is not related to this issue. Answered by email.

**Comment by mlldantas** [comment] 2021-11-25 12:01
Sure, I'll answer you via e-mail.

**Comment by minzastro** [comment] 2022-08-02 12:48
Fixed

**Closed by minzastro** 2022-08-02 12:48 UTC
Labels: installation
